Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Console-Kernel.html"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Aschedule\u0028\u0029",
            "name": "schedule",
            "summary": "Define\u0020the\u0020application\u0027s\u0020command\u0020schedule.",
            "url": "classes/App-Console-Kernel.html#method_schedule"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Acommands\u0028\u0029",
            "name": "commands",
            "summary": "Register\u0020the\u0020commands\u0020for\u0020the\u0020application.",
            "url": "classes/App-Console-Kernel.html#method_commands"
        },                {
            "fqsen": "\\App\\Enums\\TypeManyToMany",
            "name": "TypeManyToMany",
            "summary": "",
            "url": "classes/App-Enums-TypeManyToMany.html"
        },                {
            "fqsen": "\\App\\Enums\\TypeManyToMany\u003A\u003AFIRST_RANDOM",
            "name": "FIRST_RANDOM",
            "summary": "Select\u0020the\u0020systematic\u0020filling\u0020of\u0020the\ntable\u0020relative\u0020to\u0020the\u0020first\u0020model",
            "url": "classes/App-Enums-TypeManyToMany.html#enumcase_FIRST_RANDOM"
        },                {
            "fqsen": "\\App\\Enums\\TypeManyToMany\u003A\u003AFIRST_FILL",
            "name": "FIRST_FILL",
            "summary": "Select\u0020random\u0020filling\u0020of\u0020the\ntable\u0020relative\u0020to\u0020the\u0020first\u0020model",
            "url": "classes/App-Enums-TypeManyToMany.html#enumcase_FIRST_FILL"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "classes/App-Exceptions-Handler.html"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020the\u0020exception\u0020handling\u0020callbacks\u0020for\u0020the\u0020application.",
            "url": "classes/App-Exceptions-Handler.html#method_register"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontFlash",
            "name": "dontFlash",
            "summary": "The\u0020list\u0020of\u0020the\u0020inputs\u0020that\u0020are\u0020never\u0020flashed\u0020to\u0020the\u0020session\u0020on\u0020validation\u0020exceptions.",
            "url": "classes/App-Exceptions-Handler.html#property_dontFlash"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\AuthController",
            "name": "AuthController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-AuthController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\AuthController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-AuthController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\CategoryController",
            "name": "CategoryController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-CategoryController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\CategoryController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-CategoryController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\CategoryController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-CategoryController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\CategoryController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-CategoryController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\CategoryController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-CategoryController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\CategoryController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-CategoryController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameCategoryController",
            "name": "GameCategoryController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameCategoryController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameCategoryController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameCategoryController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameCategoryController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameCategoryController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameCategoryController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameCategoryController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController",
            "name": "GameController",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html#method_update"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController\u003A\u003AgetByCategoryId\u0028\u0029",
            "name": "getByCategoryId",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html#method_getByCategoryId"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api\\GameController\u003A\u003AgetByCategoryName\u0028\u0029",
            "name": "getByCategoryName",
            "summary": "",
            "url": "classes/App-Http-Controllers-Api-GameController.html#method_getByCategoryName"
        },                {
            "fqsen": "\\app\\Http\\Controllers\\Api\\StudioController",
            "name": "StudioController",
            "summary": "",
            "url": "classes/app-Http-Controllers-Api-StudioController.html"
        },                {
            "fqsen": "\\app\\Http\\Controllers\\Api\\StudioController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/app-Http-Controllers-Api-StudioController.html#method_index"
        },                {
            "fqsen": "\\app\\Http\\Controllers\\Api\\StudioController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/app-Http-Controllers-Api-StudioController.html#method_store"
        },                {
            "fqsen": "\\app\\Http\\Controllers\\Api\\StudioController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/app-Http-Controllers-Api-StudioController.html#method_show"
        },                {
            "fqsen": "\\app\\Http\\Controllers\\Api\\StudioController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/app-Http-Controllers-Api-StudioController.html#method_update"
        },                {
            "fqsen": "\\app\\Http\\Controllers\\Api\\StudioController\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/app-Http-Controllers-Api-StudioController.html#method_destroy"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Http-Kernel.html"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middleware",
            "name": "middleware",
            "summary": "The\u0020application\u0027s\u0020global\u0020HTTP\u0020middleware\u0020stack.",
            "url": "classes/App-Http-Kernel.html#property_middleware"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middlewareGroups",
            "name": "middlewareGroups",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware\u0020groups.",
            "url": "classes/App-Http-Kernel.html#property_middlewareGroups"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middlewareAliases",
            "name": "middlewareAliases",
            "summary": "The\u0020application\u0027s\u0020middleware\u0020aliases.",
            "url": "classes/App-Http-Kernel.html#property_middlewareAliases"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ApiResponse",
            "name": "ApiResponse",
            "summary": "",
            "url": "classes/App-Http-Middleware-ApiResponse.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ApiResponse\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-ApiResponse.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ApiSetAcceptRequest",
            "name": "ApiSetAcceptRequest",
            "summary": "",
            "url": "classes/App-Http-Middleware-ApiSetAcceptRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ApiSetAcceptRequest\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-ApiSetAcceptRequest.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate",
            "name": "Authenticate",
            "summary": "",
            "url": "classes/App-Http-Middleware-Authenticate.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate\u003A\u003AredirectTo\u0028\u0029",
            "name": "redirectTo",
            "summary": "Get\u0020the\u0020path\u0020the\u0020user\u0020should\u0020be\u0020redirected\u0020to\u0020when\u0020they\u0020are\u0020not\u0020authenticated.",
            "url": "classes/App-Http-Middleware-Authenticate.html#method_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies",
            "name": "EncryptCookies",
            "summary": "",
            "url": "classes/App-Http-Middleware-EncryptCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020cookies\u0020that\u0020should\u0020not\u0020be\u0020encrypted.",
            "url": "classes/App-Http-Middleware-EncryptCookies.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "name": "PreventRequestsDuringMaintenance",
            "summary": "",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020reachable\u0020while\u0020maintenance\u0020mode\u0020is\u0020enabled.",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated",
            "name": "RedirectIfAuthenticated",
            "summary": "",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings",
            "name": "TrimStrings",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrimStrings.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020attributes\u0020that\u0020should\u0020not\u0020be\u0020trimmed.",
            "url": "classes/App-Http-Middleware-TrimStrings.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts",
            "name": "TrustHosts",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustHosts.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts\u003A\u003Ahosts\u0028\u0029",
            "name": "hosts",
            "summary": "Get\u0020the\u0020host\u0020patterns\u0020that\u0020should\u0020be\u0020trusted.",
            "url": "classes/App-Http-Middleware-TrustHosts.html#method_hosts"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies",
            "name": "TrustProxies",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustProxies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024proxies",
            "name": "proxies",
            "summary": "The\u0020trusted\u0020proxies\u0020for\u0020this\u0020application.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_proxies"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "The\u0020headers\u0020that\u0020should\u0020be\u0020used\u0020to\u0020detect\u0020proxies.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_headers"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ValidateSignature",
            "name": "ValidateSignature",
            "summary": "",
            "url": "classes/App-Http-Middleware-ValidateSignature.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\ValidateSignature\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020query\u0020string\u0020parameters\u0020that\u0020should\u0020be\u0020ignored.",
            "url": "classes/App-Http-Middleware-ValidateSignature.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken",
            "name": "VerifyCsrfToken",
            "summary": "",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020excluded\u0020from\u0020CSRF\u0020verification.",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Auth\\LoginRequest",
            "name": "LoginRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-Auth-LoginRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Auth\\LoginRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-Auth-LoginRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Auth\\LoginRequest\u003A\u003Amessages\u0028\u0029",
            "name": "messages",
            "summary": "Custom\u0020messages\u0020for\u0020rules",
            "url": "classes/App-Http-Requests-Api-Auth-LoginRequest.html#method_messages"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Auth\\LoginRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-Auth-LoginRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Category\\PatchRequest",
            "name": "PatchRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-Category-PatchRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Category\\PatchRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-Category-PatchRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Category\\PatchRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-Category-PatchRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Category\\StoreRequest",
            "name": "StoreRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-Category-StoreRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Category\\StoreRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-Category-StoreRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Category\\StoreRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-Category-StoreRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\PatchRequest",
            "name": "PatchRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-Game-PatchRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\PatchRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-Game-PatchRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\PatchRequest\u003A\u003Amessages\u0028\u0029",
            "name": "messages",
            "summary": "Custom\u0020messages\u0020for\u0020rules",
            "url": "classes/App-Http-Requests-Api-Game-PatchRequest.html#method_messages"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\PatchRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-Game-PatchRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\StoreRequest",
            "name": "StoreRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-Game-StoreRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\StoreRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-Game-StoreRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\StoreRequest\u003A\u003Amessages\u0028\u0029",
            "name": "messages",
            "summary": "Custom\u0020messages\u0020for\u0020rules",
            "url": "classes/App-Http-Requests-Api-Game-StoreRequest.html#method_messages"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game\\StoreRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-Game-StoreRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\PatchRequest",
            "name": "PatchRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-GameCategory-PatchRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\PatchRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-GameCategory-PatchRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\PatchRequest\u003A\u003Amessages\u0028\u0029",
            "name": "messages",
            "summary": "Custom\u0020messages\u0020for\u0020rules",
            "url": "classes/App-Http-Requests-Api-GameCategory-PatchRequest.html#method_messages"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\PatchRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-GameCategory-PatchRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\StoreRequest",
            "name": "StoreRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-GameCategory-StoreRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\StoreRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-GameCategory-StoreRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\StoreRequest\u003A\u003Amessages\u0028\u0029",
            "name": "messages",
            "summary": "Custom\u0020messages\u0020for\u0020rules",
            "url": "classes/App-Http-Requests-Api-GameCategory-StoreRequest.html#method_messages"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory\\StoreRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-GameCategory-StoreRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Studio\\PatchRequest",
            "name": "PatchRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-Studio-PatchRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Studio\\PatchRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-Studio-PatchRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Studio\\PatchRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-Studio-PatchRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Studio\\StoreRequest",
            "name": "StoreRequest",
            "summary": "",
            "url": "classes/App-Http-Requests-Api-Studio-StoreRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Studio\\StoreRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-Api-Studio-StoreRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Studio\\StoreRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-Api-Studio-StoreRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Category\\CategoryCollection",
            "name": "CategoryCollection",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Category-CategoryCollection.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Category\\CategoryCollection\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020collection\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Category-CategoryCollection.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Category\\GetResource",
            "name": "GetResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Category-GetResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Category\\GetResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Category-GetResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Category\\PostResource",
            "name": "PostResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Category-PostResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Category\\PostResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Category-PostResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Game\\GameCollection",
            "name": "GameCollection",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Game-GameCollection.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Game\\GameCollection\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020collection\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Game-GameCollection.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Game\\GetResource",
            "name": "GetResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Game-GetResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Game\\GetResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Game-GetResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Game\\PostResource",
            "name": "PostResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Game-PostResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Game\\PostResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Game-PostResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\GameCategory\\GameCategoryCollection",
            "name": "GameCategoryCollection",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-GameCategory-GameCategoryCollection.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\GameCategory\\GameCategoryCollection\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020collection\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-GameCategory-GameCategoryCollection.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\GameCategory\\GetResource",
            "name": "GetResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-GameCategory-GetResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\GameCategory\\GetResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-GameCategory-GetResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\GameCategory\\PostResource",
            "name": "PostResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-GameCategory-PostResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\GameCategory\\PostResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-GameCategory-PostResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Studio\\GetResource",
            "name": "GetResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Studio-GetResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Studio\\GetResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Studio-GetResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Studio\\PostResource",
            "name": "PostResource",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Studio-PostResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Studio\\PostResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Studio-PostResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Studio\\StudioCollection",
            "name": "StudioCollection",
            "summary": "",
            "url": "classes/App-Http-Resources-Api-Studio-StudioCollection.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Studio\\StudioCollection\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020collection\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-Api-Studio-StudioCollection.html#method_toArray"
        },                {
            "fqsen": "\\App\\Models\\Category",
            "name": "Category",
            "summary": "",
            "url": "classes/App-Models-Category.html"
        },                {
            "fqsen": "\\App\\Models\\Category\u003A\u003AgameCategories\u0028\u0029",
            "name": "gameCategories",
            "summary": "",
            "url": "classes/App-Models-Category.html#method_gameCategories"
        },                {
            "fqsen": "\\App\\Models\\Category\u003A\u003Agames\u0028\u0029",
            "name": "games",
            "summary": "",
            "url": "classes/App-Models-Category.html#method_games"
        },                {
            "fqsen": "\\App\\Models\\Category\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Category.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Game",
            "name": "Game",
            "summary": "",
            "url": "classes/App-Models-Game.html"
        },                {
            "fqsen": "\\App\\Models\\Game\u003A\u003AgameCategories\u0028\u0029",
            "name": "gameCategories",
            "summary": "",
            "url": "classes/App-Models-Game.html#method_gameCategories"
        },                {
            "fqsen": "\\App\\Models\\Game\u003A\u003Acategories\u0028\u0029",
            "name": "categories",
            "summary": "",
            "url": "classes/App-Models-Game.html#method_categories"
        },                {
            "fqsen": "\\App\\Models\\Game\u003A\u003Astudio\u0028\u0029",
            "name": "studio",
            "summary": "",
            "url": "classes/App-Models-Game.html#method_studio"
        },                {
            "fqsen": "\\App\\Models\\Game\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Game.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Game\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "",
            "url": "classes/App-Models-Game.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\GameCategory",
            "name": "GameCategory",
            "summary": "",
            "url": "classes/App-Models-GameCategory.html"
        },                {
            "fqsen": "\\App\\Models\\GameCategory\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-GameCategory.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\GameCategory\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-GameCategory.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Studio",
            "name": "Studio",
            "summary": "",
            "url": "classes/App-Models-Studio.html"
        },                {
            "fqsen": "\\App\\Models\\Studio\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Studio.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider",
            "name": "AuthServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AuthServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020authentication\u0020\/\u0020authorization\u0020services.",
            "url": "classes/App-Providers-AuthServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003A\u0024policies",
            "name": "policies",
            "summary": "The\u0020model\u0020to\u0020policy\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-AuthServiceProvider.html#property_policies"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider",
            "name": "BroadcastServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-BroadcastServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-BroadcastServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider",
            "name": "EventServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-EventServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020events\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003AshouldDiscoverEvents\u0028\u0029",
            "name": "shouldDiscoverEvents",
            "summary": "Determine\u0020if\u0020events\u0020and\u0020listeners\u0020should\u0020be\u0020automatically\u0020discovered.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_shouldDiscoverEvents"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003A\u0024listen",
            "name": "listen",
            "summary": "The\u0020event\u0020to\u0020listener\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#property_listen"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider",
            "name": "RouteServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-RouteServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Define\u0020your\u0020route\u0020model\u0020bindings,\u0020pattern\u0020filters,\u0020and\u0020other\u0020route\u0020configuration.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AHOME",
            "name": "HOME",
            "summary": "The\u0020path\u0020to\u0020your\u0020application\u0027s\u0020\u0022home\u0022\u0020route.",
            "url": "classes/App-Providers-RouteServiceProvider.html#constant_HOME"
        },                {
            "fqsen": "\\App\\Services\\Api\\ActionDefaultPost",
            "name": "ActionDefaultPost",
            "summary": "",
            "url": "classes/App-Services-Api-ActionDefaultPost.html"
        },                {
            "fqsen": "\\App\\Services\\Api\\ActionDefaultPost\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "",
            "url": "classes/App-Services-Api-ActionDefaultPost.html#method_store"
        },                {
            "fqsen": "\\App\\Services\\Api\\ActionDefaultPost\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Services-Api-ActionDefaultPost.html#method_update"
        },                {
            "fqsen": "\\App\\Services\\Api\\ActionDefaultPost\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "",
            "url": "classes/App-Services-Api-ActionDefaultPost.html#method_destroy"
        },                {
            "fqsen": "\\App\\Services\\Api\\Game\\GameService",
            "name": "GameService",
            "summary": "",
            "url": "classes/App-Services-Api-Game-GameService.html"
        },                {
            "fqsen": "\\App\\Services\\Api\\Game\\GameService\u003A\u003AgetByCategory\u0028\u0029",
            "name": "getByCategory",
            "summary": "",
            "url": "classes/App-Services-Api-Game-GameService.html#method_getByCategory"
        },                {
            "fqsen": "\\App\\Services\\Api\\Studio\\StudioService",
            "name": "StudioService",
            "summary": "",
            "url": "classes/App-Services-Api-Studio-StudioService.html"
        },                {
            "fqsen": "\\App\\Traits\\SeederManyToMany",
            "name": "SeederManyToMany",
            "summary": "",
            "url": "classes/App-Traits-SeederManyToMany.html"
        },                {
            "fqsen": "\\App\\Traits\\SeederManyToMany\u003A\u003Afill\u0028\u0029",
            "name": "fill",
            "summary": "",
            "url": "classes/App-Traits-SeederManyToMany.html#method_fill"
        },                {
            "fqsen": "\\App\\Traits\\SeederManyToMany\u003A\u003A\u0024firstFK",
            "name": "firstFK",
            "summary": "",
            "url": "classes/App-Traits-SeederManyToMany.html#property_firstFK"
        },                {
            "fqsen": "\\App\\Traits\\SeederManyToMany\u003A\u003A\u0024secondFK",
            "name": "secondFK",
            "summary": "",
            "url": "classes/App-Traits-SeederManyToMany.html#property_secondFK"
        },                {
            "fqsen": "\\App\\Traits\\SeederManyToMany\u003A\u003A\u0024secondModelId",
            "name": "secondModelId",
            "summary": "",
            "url": "classes/App-Traits-SeederManyToMany.html#property_secondModelId"
        },                {
            "fqsen": "\\Database\\Factories\\CategoryFactory",
            "name": "CategoryFactory",
            "summary": "",
            "url": "classes/Database-Factories-CategoryFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\CategoryFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-CategoryFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\GameCategoryFactory",
            "name": "GameCategoryFactory",
            "summary": "",
            "url": "classes/Database-Factories-GameCategoryFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\GameCategoryFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-GameCategoryFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\GameFactory",
            "name": "GameFactory",
            "summary": "",
            "url": "classes/Database-Factories-GameFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\GameFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-GameFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\StudioFactory",
            "name": "StudioFactory",
            "summary": "",
            "url": "classes/Database-Factories-StudioFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\StudioFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-StudioFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory",
            "name": "UserFactory",
            "summary": "",
            "url": "classes/Database-Factories-UserFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UserFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Seeders\\CategorySeeder",
            "name": "CategorySeeder",
            "summary": "",
            "url": "classes/Database-Seeders-CategorySeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\CategorySeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-CategorySeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\GameCategorySeeder",
            "name": "GameCategorySeeder",
            "summary": "",
            "url": "classes/Database-Seeders-GameCategorySeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\GameCategorySeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-GameCategorySeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\GameSeeder",
            "name": "GameSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-GameSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\GameSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-GameSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\StudioSeeder",
            "name": "StudioSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-StudioSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\StudioSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-StudioSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\UserSeeder",
            "name": "UserSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-UserSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\UserSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-UserSeeder.html#method_run"
        },                {
            "fqsen": "\\LARAVEL_START",
            "name": "LARAVEL_START",
            "summary": "",
            "url": "namespaces/default.html#constant_LARAVEL_START"
        },                {
            "fqsen": "\\Tests\\CreatesApplication",
            "name": "CreatesApplication",
            "summary": "",
            "url": "classes/Tests-CreatesApplication.html"
        },                {
            "fqsen": "\\Tests\\CreatesApplication\u003A\u003AcreateApplication\u0028\u0029",
            "name": "createApplication",
            "summary": "Creates\u0020the\u0020application.",
            "url": "classes/Tests-CreatesApplication.html#method_createApplication"
        },                {
            "fqsen": "\\Tests\\Feature\\Api\\GameTest",
            "name": "GameTest",
            "summary": "",
            "url": "classes/Tests-Feature-Api-GameTest.html"
        },                {
            "fqsen": "\\Tests\\Feature\\Api\\GameTest\u003A\u003Aa_game_can_be_stored\u0028\u0029",
            "name": "a_game_can_be_stored",
            "summary": "",
            "url": "classes/Tests-Feature-Api-GameTest.html#method_a_game_can_be_stored"
        },                {
            "fqsen": "\\Tests\\TestCase",
            "name": "TestCase",
            "summary": "",
            "url": "classes/Tests-TestCase.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Unit-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest\u003A\u003Atest_that_true_is_true\u0028\u0029",
            "name": "test_that_true_is_true",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Unit-ExampleTest.html#method_test_that_true_is_true"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/app-enums.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/app-http-controllers-api.html"
        },                {
            "fqsen": "\\app\\Http\\Controllers\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/app-http-controllers-api.html"
        },                {
            "fqsen": "\\app\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\app\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\app",
            "name": "app",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/app-http-requests-api-auth.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/app-http-requests-api.html"
        },                {
            "fqsen": "\\App\\Http\\Requests",
            "name": "Requests",
            "summary": "",
            "url": "namespaces/app-http-requests.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Category",
            "name": "Category",
            "summary": "",
            "url": "namespaces/app-http-requests-api-category.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Game",
            "name": "Game",
            "summary": "",
            "url": "namespaces/app-http-requests-api-game.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\GameCategory",
            "name": "GameCategory",
            "summary": "",
            "url": "namespaces/app-http-requests-api-gamecategory.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\Api\\Studio",
            "name": "Studio",
            "summary": "",
            "url": "namespaces/app-http-requests-api-studio.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Category",
            "name": "Category",
            "summary": "",
            "url": "namespaces/app-http-resources-api-category.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/app-http-resources-api.html"
        },                {
            "fqsen": "\\App\\Http\\Resources",
            "name": "Resources",
            "summary": "",
            "url": "namespaces/app-http-resources.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Game",
            "name": "Game",
            "summary": "",
            "url": "namespaces/app-http-resources-api-game.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\GameCategory",
            "name": "GameCategory",
            "summary": "",
            "url": "namespaces/app-http-resources-api-gamecategory.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\Api\\Studio",
            "name": "Studio",
            "summary": "",
            "url": "namespaces/app-http-resources-api-studio.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\App\\Services\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/app-services-api.html"
        },                {
            "fqsen": "\\App\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-services.html"
        },                {
            "fqsen": "\\App\\Services\\Api\\Game",
            "name": "Game",
            "summary": "",
            "url": "namespaces/app-services-api-game.html"
        },                {
            "fqsen": "\\App\\Services\\Api\\Studio",
            "name": "Studio",
            "summary": "",
            "url": "namespaces/app-services-api-studio.html"
        },                {
            "fqsen": "\\App\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/app-traits.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        },                {
            "fqsen": "\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/tests.html"
        },                {
            "fqsen": "\\Tests\\Feature\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/tests-feature-api.html"
        },                {
            "fqsen": "\\Tests\\Feature",
            "name": "Feature",
            "summary": "",
            "url": "namespaces/tests-feature.html"
        },                {
            "fqsen": "\\Tests\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "namespaces/tests-unit.html"
        }            ]
);
